Multivio Server
===============
Johnny Mariethoz <Johnny.Mariethoz@rero.ch>
V. 0.0, 2010/02/10

== Introduction ==
Python based multivio server.

== Installation ==

.An Used packages
[width="80%",frame="topbot",options="header"]
|========================================================================================================================
|Packages   |Documentation                                 |Licence        |2.5 Installation          |2.6 Installation
|wsgiref    |http://docs.python.org/library/wsgiref.html   |PSF-2          |easy_install wsgiref      |default
|json       |http://docs.python.org/library/json.html      |PSF-2          |easy_install simplejson   |default
|PIL        |http://www.pythonware.com/products/pil        |MIT like       |setup.py                  |easy_install
|pyPdf      |http://pybrary.net/pyPdf/                     |modified BSD   |setup.py                  |easy_install
|========================================================================================================================

The PIL library need also libjpeg as describe in the PIL documentation.

== Debian Packages ==

=====================
---------------------
apt-get install libapache2-mod-wsgi python-imaging python-simplejson
apt-get install openssh-server
apt-get install swig
apt-get install libpoppler-dev
apt-get install g++
apt-get install python-dev
apt-get install python-pypdf
apt-get install ttf-freefont
apt-get install gsfonts gsfonts-x11
---------------------
=====================

== With apache ==
First you need to install the project itself:
python setup.py install --home /var/www/multivio

Then rename the sample config file:

cd /var/www/multivio/bin
mv mvo_config_example.py mvo_config.py
and change it.

If you decide to change the temp directory, do not forget to adapt the user right:

chown www-data /var/www/multivio/temp
for example.


Modify the apache config file. For example:
=====================
---------------------
<Directory /var/www/multivio>
Order allow,deny
Allow from all
</Directory>
ErrorLog /var/www/multivio/log/apache.err
WSGIPythonPath /var/www/multivio/lib/python:/var/www/multivio/bin
LogLevel debug
WSGIScriptAlias /server /var/www/multivio/bin/multivio_server.py
---------------------
=====================
And restart apache.



=== HowTo Install a Python Package ===

The simplest way is to use easy_install by running:

sudo easy_install <package_name>.

If the package does not exists or if easy_install crashed you can install a
python package by downloading the sources and running:
=====================
---------------------
python setup.py build
python setup.py install --home $HOME
---------------------
=====================

You need to set the environment variable PYTHONPATH to $HOME/lib/python:
=====================
---------------------
export PYTHONPATH=$PYTHONPATH:$HOME/lib/python
---------------------
=====================

In 2.6 you can run:

=====================
---------------------
python setup.py install --user
---------------------
=====================
instead. No environment variable is needed.

== Usage ==

You can run a local server as:
=====================
---------------------
python build_dir/lib*/dispatcher.py
---------------------
=====================

You can now access it at __http://localhost:4041__

== TODO ==

- error, message defintion for client/sever communication

- home made or existing http python framework

- replace pdf library by http://poppler.freedesktop.org using a python wrapper
	such as: swig


== Questions ==

- do I download a content file on the server even if I will not modify it
